version: "3"
services:
  golang:
    image: golang:latest
    container_name: babylon-golang
    volumes:
      - ../:/go/src/babylon-stack
    working_dir: /go/src/babylon-stack    
    command: go run main.go
  
  mongo: 
    image: mongo:latest
    container_name: babylon-mongodb
    volumes:
      - ${PWD}/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=babylon
    ports:
    - "27017:27017" 